### ISSUE TITLE
Helpers available on server

### ISSUE THREAD

**Issue by danielparas** [arillo/meteor-flow-router-helpers#28]
Hi, thanks for this great package!

Is there a way to make the helpers accessible on the server? I'm using `meteorhacks:ssr` and `meteorhacks:picker` to generate SEO friendly versions of the client side and naturally I'll need the helpers like `pathFor` to be able to easily generate the URLs.

I tested creating the helper on the server side using the code from this repo and `pathFor` worked perfectly with no modifications from my end - just copy and paste. (since `Flowrouter` is available on the server even though it does not have routing capabilities there)

On server:

```
Template.registerHelper "pathFor", (path, view) ->
  throw new Error('no path defined') unless path
  if path.hash?.route?
    view = path
    path = view.hash.route
    delete view.hash.route
  query = if view.hash.query then FlowRouter._qs.parse(view.hash.query) else {}
  hashBang = if view.hash.hash then view.hash.hash else ''
  FlowRouter.path(path, view.hash, query) + hashBang
```

The above worked flawlessly

Looking forward to your response.

**Comment by banglashi** [comment]
Hi @danielparas 

I looked into it, shouldn't be a problem. The only helpers currently interesting on the server side would be pathFor and urlFor, right? 

I would export the helpers via FlowRouterHelpers, does that sound ok?

I also did some modification to the pathFor method so you can call it directly like this:

`FlowRouterHelpers.pathFor('/post/:id',{ id:'12345' })`

instead of having to pass 

`FlowRouterHelpers.pathFor('/post/:id',{ hash: {id: '12345' }})`

Let me know if that would work for you and I will publish an update.

**Comment by joarobles** [comment]
Sounds pretty good to me, came here looking exactly the same as danielparas

**Comment by danielparas** [comment]
Sounds good to me too! thanks a lot @banglashi
